name: Build Binaries

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      build-debug-info:
        description: 'Profile and debug the build process'
        required: false
        default: false
        type: boolean
      use-ccache:
        description: 'Enable ccache/sccache'
        required: false
        default: true
        type: boolean
  pull_request:
  push:
    branches:
    - '**'              # every branch
    - '!no-build-**'    # unless marked as no-build

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm-cache
  base-configure-command: >-
    cmake -B build
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
    -DGEODE_CODEGEN_CMAKE_ARGS="-DCMAKE_C_COMPILER=clang;-DCMAKE_CXX_COMPILER=clang++;-G Ninja"
    -G Ninja
  base-build-command: |
    cmake --build build --config RelWithDebInfo --parallel
    rm bin/nightly/resources/.geode_cache

jobs:
  build-android:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Android (32-bit)
          id: android32
          extra-configure: -DANDROID_ABI=armeabi-v7a

        - name: Android (64-bit)
          id: android64
          extra-configure: -DANDROID_ABI=arm64-v8a

    name: Build ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Prepare for Build Debug Info
      id: build-debug-info
      uses: ./.github/actions/build-debug-info
      with:
        has-sccache: ${{ inputs.use-ccache }}
      if: inputs.build-debug-info

    - name: Setup caches
      uses: ./.github/actions/setup-cache
      with:
        host: linux
        target: ${{ matrix.config.id }}
        use-ccache: ${{ github.event_name != 'workflow_dispatch' || inputs.use-ccache }}

    - name: Setup Ninja
      uses: ./.github/actions/setup-ninja
      with:
        host: linux

    - name: Setup CLI
      uses: geode-sdk/cli/.github/actions/setup@main

    - name: Setup Breakpad Tools
      uses: ./.github/actions/setup-dump-sym
      id: breakpad-tools

    - name: Fix Ubuntu libcstd++
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install --only-upgrade libstdc++6

    - name: Configure
      run: >
        ${{ env.base-configure-command }}
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_CXX_COMPILER=clang++
        -DANDROID_PLATFORM=android-23
        -DANDROID_STL=c++_shared
        ${{ matrix.config.extra-configure }}
        ${{ steps.build-debug-info.outputs.extra-configure }}

    - name: Build
      run: |
        ${{ env.base-build-command }}
        ${{ steps.build-debug-info.outputs.extra-build }}

    # hardcoding toolchain path :(
    - name: Dump Symbols
      run: |
        ${{ steps.breakpad-tools.outputs.binary-path }} ./bin/nightly/Geode.${{ matrix.config.id }}.so -o ./bin/nightly/Geode.${{ matrix.config.id }}.so.sym
        $ANDROID_NDK_LATEST_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip ./bin/nightly/Geode.${{ matrix.config.id }}.so

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: geode-${{ matrix.config.id }}
        path: ./bin/nightly

    - name: Complete Build Debug Info
      uses: ./.github/actions/build-debug-info-post
      with:
        target: ${{ matrix.config.id }}
      if: inputs.build-debug-info && (success() || failure())

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [ build-android ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Declare Version Variables
        id: ref
        run: |
          echo "version=$(cat VERSION | xargs)" >> $GITHUB_OUTPUT
          echo "hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Zip Android32 Artifacts
        uses: vimtor/action-zip@v1.2
        with:
          files: geode-android32/Geode.android32.so geode-android32/Geode.android32.so.sym
          dest: geode-${{ steps.ref.outputs.hash }}-android32.zip

      - name: Zip Android64 Artifacts
        uses: vimtor/action-zip@v1.2
        with:
          files: geode-android64/Geode.android64.so geode-android64/Geode.android64.so.sym
          dest: geode-${{ steps.ref.outputs.hash }}-android64.zip

      - name: Zip Resources
        uses: vimtor/action-zip@v1.2
        with:
          files: geode-android64/resources
          dest: resources.zip

      - name: Update Development Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Development Release'
          body: |
            Geode development release for commit ${{ github.sha }}. Since this is not a regular release, Geode will not install the resources automatically, so you should use the installer if you want them.
          files: |
            ./geode-${{ steps.ref.outputs.hash }}-android32.zip
            ./geode-${{ steps.ref.outputs.hash }}-android64.zip
            ./resources.zip
